require "options"
require "keymaps"
require "config.plugins"
require "config.colorscheme"
require "config.colorizer"
require "config.cmp"
require "config.lsp"
require "config.markdown"
require "config.telescope"
require "config.treesitter"
require "config.autopairs"
require "config.gitsigns"
require'nvim-tree'.setup{}
--require "config.nvim-tree"
require "config.toggleterm"
require "config.zen-mode"
